version: '3.7'

services:
    nginx:
        container_name: marydo_nginx_dev
        image: nginx
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d
            - ./:/app
        links:
            - php-fpm
        ports:
            - '8000:80'

    php-fpm:
        container_name: market_php-fpm
        build:
            context: docker
            dockerfile: php-fpm/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        working_dir: /app

    php-cli:
        container_name: market_php-cli
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./:/app

    api-postgres:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
           - "127.0.0.1:5432:5432"