version: '3.7'

services:
    api:
        image: nginx
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/app
        restart: always
        depends_on:
            - php-fpm

    php-fpm:
        container_name: market_php-fpm
        command: php -S 0.0.0.0:8080 -t public
        build:
            context: docker
            dockerfile: php-fpm/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        ports:
            - 8080:8080
        volumes:
            - ./:/app
        working_dir: /app

    php-cli:
        container_name: market_php-cli
        build:
            context: docker
            dockerfile: php-cli/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./:/app